### PR TITLE
DM-39313: Remove lsst-efd-client, now in conda.

### PR DESCRIPTION
**Pull request by ktlim**
Do not merge until https://github.com/conda-forge/rubinenv-feedstock/pull/161 merges.

### CODE REVIEW

**Review by athornton — APPROVED** [review]
Every little bit helps!

**Comment by athornton** [comment]
Whoopsie.

**Comment by athornton** [comment]
Except: merge it to main, rebase prod-update from main, merge prod-update to prod.

**Comment by ktlim** [comment]
Replaced by #131.

**Pull request closed without merging**
